BT 4987
hotstar/hotstar-github-action-workflows pull request #23
Opened 2022-06-21 05:00 UTC by Shanmugapriya03

2022-06-24 03:33 UTC, raj-dhamsaniya requested changes
please check the parameters in all the files. commented on one only.

2022-06-24 03:33 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      DEPLOYMENT_MANIFEST_FROM_REPO:
why its needed? if its not from the DP, then APP_ID would be `''` no? LMK if it is used for any other purpose

2022-06-24 03:33 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      CLUSTER:
Will there be any instance where this will be changed? as we are using only one cluster? also, in case it changes, just changing here will do the change for everywhere, right?! so it should not be the choice we should manage at each repo level.

2022-06-24 03:33 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      APP_NAME:
If APP_ID is there, then whatever before first `.` will be app name, no? IMO, this also can be removed

2022-06-24 03:33 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      TEST_ENV_SERVICE_URL:
Will there be any instance where this will be changed? as we are using only one service to get new feature env details?

2022-06-24 03:33 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      VAULT_PATH:
This can be configured as a service variable in harness and removed from here.

2022-06-24 03:33 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      ENDGAME_ENDPOINT:
this will be same for each feature env, right? there is no need for the var.

2022-06-24 03:33 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      FEATURE_ENV_ONBOARDED:
it can be removed, as if serviceName is provided, feature env is onboarded.

2022-06-24 05:14 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      DEPLOYMENT_MANIFEST_FROM_REPO:
`DEPLOYMENT_MANIFEST_FROM_REPO` is a boolean input, if it is false `APP_ID` is needed

2022-06-24 05:18 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      DEPLOYMENT_MANIFEST_FROM_REPO:
this can be resolved using `FEATURE_ENV_ONBOARDED` var. if its true, and app id is `''` then it is manifest based process, right? if `FEATURE_ENV_ONBOARDED` is true and appid is not provided you can throw error as well

2022-06-24 05:19 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      CLUSTER:
Similar reason as DOCKER_REGISTRY, we have feature env in both pre-prod and dev cluster
dev - https://k8s-dash-dev-aps1.np.hotstar-labs.com/#/pod?namespace=feature-env
preprod - https://k8s-dash-nonprod-aps1.pp.hotstar-labs.com/#/pod?namespace=feature-env

2022-06-24 05:20 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-go-ci-workflow.yml
> +      TEST_ENV_SERVICE_URL:
Same reason we have both in dev and pp
https://testenvironment.dev.hotstar-labs.com/swagger-ui.html
https://testenvironment.pp.hotstar-labs.com/swagger-ui.html

2022-06-24 05:21 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      ENDGAME_ENDPOINT:
Different endpoint for dev and pp

2022-06-24 05:22 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      ENDGAME_ENDPOINT:
there is a dev endgame service for the dev cluster? AFAIK, we use one for mena and one for all other envs

2022-06-24 05:25 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      FEATURE_ENV_ONBOARDED:
Ya it can be done, but it will create confusion as this can't be a deciding variable (SERVICE_NAME) in `go-ci-workflow` I want to follow a uniform approach for both create and delete feature envs

2022-06-24 06:44 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      ENDGAME_ENDPOINT:
ok will change it

2022-06-28 13:26 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-go-pr-check-workflow.yml
> +      VAULT_PATH:
moved as service variable

2022-06-29 06:13 UTC, raj-dhamsaniya requested changes

2022-06-29 06:13 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-js-pr-check-workflow.yml
> +      FEATURE_ENV_ONBOARDED:
can we give default as false?

2022-06-29 06:13 UTC, raj-dhamsaniya commented on .github/workflows/hotstar-js-pr-check-workflow.yml
> +      DOCKER_ARGUMENTS_STRING:
if not required we can give default for every var

2022-06-29 07:03 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-js-pr-check-workflow.yml
> +      FEATURE_ENV_ONBOARDED:
done

2022-06-29 07:04 UTC, Shanmugapriya03 commented on .github/workflows/hotstar-js-pr-check-workflow.yml
> +      DOCKER_ARGUMENTS_STRING:
added possible defaults values for some variables

2022-06-29 07:27 UTC, raj-dhamsaniya approved these changes
LGTM. @ajaychoudhary-hotstar all additional params are not required and current jobs should not be affected. Please review as well.

2022-06-29 08:41 UTC, ajaychoudhary-hotstar approved these changes

2022-06-29 08:42 UTC, merged